name: Build Check for GRUB x64

on:
  push:
    branches: [main dev-riscv]
  pull_request:
    branches: [main dev-riscv]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang cmake pkg-config nasm xorriso mtools

      - name: Build project
        run: make BOOTLOADER=grub ARCH=x86_64 -j
